### ISSUE TITLE
INFO:openai:error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False

### ISSUE THREAD

**Issue by lywa3** [abryant710/auto-codebase-documenter#3]
Traceback (most recent call last):
  File "/home/devly/PycharmProjects/restaurant_lemy/venv/bin/auto-codebase-documenter", line 8, in <module>
    sys.exit(main())
  File "/home/devly/PycharmProjects/restaurant_lemy/venv/lib/python3.10/site-packages/auto_codebase_documenter/auto_documenter.py", line 114, in main
    document_code(
  File "/home/devly/PycharmProjects/restaurant_lemy/venv/lib/python3.10/site-packages/auto_codebase_documenter/auto_documenter.py", line 55, in document_code
    documenter.process_all_files()
  File "/home/devly/PycharmProjects/restaurant_lemy/venv/lib/python3.10/site-packages/auto_codebase_documenter/AutoCodebaseDocumenter.py", line 191, in process_all_files
    success, message = self._process_file(file_path)
  File "/home/devly/PycharmProjects/restaurant_lemy/venv/lib/python3.10/site-packages/auto_codebase_documenter/AutoCodebaseDocumenter.py", line 174, in _process_file
    response = self._get_completion(prompt)
  File "/home/devly/PycharmProjects/restaurant_lemy/venv/lib/python3.10/site-packages/auto_codebase_documenter/AutoCodebaseDocumenter.py", line 100, in _get_completion
    response = openai.ChatCompletion.create(
  File "/home/devly/PycharmProjects/restaurant_lemy/venv/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/devly/PycharmProjects/restaurant_lemy/venv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/devly/PycharmProjects/restaurant_lemy/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/devly/PycharmProjects/restaurant_lemy/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/devly/PycharmProjects/restaurant_lemy/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

**Comment by abryant710** [comment]
Thanks for pointing this out. I need to add better error handling for this.

Seems like you need to top up your account balance on your Open AI account to overcome the error for now.

Next version of the tool will handle this error more gracefully.
